fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "concat": "git://github.com/ripienaar/puppet-concat.git"
    "apache": "git://github.com/puppetlabs/puppetlabs-apache"
    "python": "git://github.com/stankevich/puppet-python"
  symlinks:
    graphite: "#{source_dir}"
